// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSPre4qnGOlyLV_o_NzHLkRutlXMCtdNU',
    appId: '1:1036037204076:web:4c550e252edba3c0511049',
    messagingSenderId: '1036037204076',
    projectId: 'student-directory-app-b29ef',
    authDomain: 'student-directory-app-b29ef.firebaseapp.com',
    storageBucket: 'student-directory-app-b29ef.firebasestorage.app',
    measurementId: 'G-3G6ZTWJZ1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIXcaztLnuYPrKBvuEnAvlDOLEc1qkMI',
    appId: '1:1036037204076:android:1d77d17977e21f52511049',
    messagingSenderId: '1036037204076',
    projectId: 'student-directory-app-b29ef',
    storageBucket: 'student-directory-app-b29ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7H4RZ0NKcC9jhogaTpOSmruRFiiyJjNw',
    appId: '1:1036037204076:ios:656f44d879f2c894511049',
    messagingSenderId: '1036037204076',
    projectId: 'student-directory-app-b29ef',
    storageBucket: 'student-directory-app-b29ef.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7H4RZ0NKcC9jhogaTpOSmruRFiiyJjNw',
    appId: '1:1036037204076:ios:656f44d879f2c894511049',
    messagingSenderId: '1036037204076',
    projectId: 'student-directory-app-b29ef',
    storageBucket: 'student-directory-app-b29ef.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSPre4qnGOlyLV_o_NzHLkRutlXMCtdNU',
    appId: '1:1036037204076:web:93fcd9628ca0ea6b511049',
    messagingSenderId: '1036037204076',
    projectId: 'student-directory-app-b29ef',
    authDomain: 'student-directory-app-b29ef.firebaseapp.com',
    storageBucket: 'student-directory-app-b29ef.firebasestorage.app',
    measurementId: 'G-V7X26KM7MT',
  );
}
